name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        yarn install
        yarn run build
    - name: Firebase Deploy
      run: |
        sudo yarn add -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}



